### ISSUE TITLE
Player 2 crashed on flop

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#27]
After the betting round of bet and call, Player 2 has crashed.

Screenshot: http://i.norbert.dev/50f7db

`Bus error (core dumped)`

No backtrace.

**Comment by norbertdragan** [comment]
Happened again with no backtrace.

Screenshot: https://i.norbert.dev/6288af

**Comment by sg777** [comment]
Since the issue is with improper handling of communication between the threads,  I fixed this crashing issue in the latest commit. Please check and revert if the issue persists.
