### ISSUE TITLE
toCall and toRaise are different for the small blind and big blind

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#32]
Pre-flop the small blind receives`toCall: 2m, toRaise: 4m` while the big blind receives `toCall: 0, toRaise: 2m`. For both players, the value values should be `toCall: 2m, toRaise: 4m`, since `2m` is the largest bet that needs to be called, and the minimum raise is to `4m`.

Screenshot: http://i.norbert.dev/feebc9 (it was made after the small blind has called, but the message was received right at the betting rounds for each player).

**Comment by sg777** [comment]
The small blind and big blind values are automated in the back end, I guess the message which you referring is the players turn after the big blind. Please check and let me know if this is an issue?

**Comment by norbertdragan** [comment]
I cannot fire up the game now, but my main problem is that these numbers don't add up.

*Option A:* If the backend sends relative amounts (i.e. "this much _more_ the player has to put in order to do the action"), then the values should be:
- Small Blind: `toCall: 1000000, toRaise: 2000000`
- Big Blind: `toCall: 0, toRaise: 2000000`

*Option B:* If the backend sends total amounts (i.e. "this is how much _total_ the player has to put in to do the action), then the values should be:
- Small Blind: `toCall: 2000000, toRaise: 4000000`
- Big Blind: `toCall: 2000000, toRaise: 4000000`

However, currently we have these values:
- Small Blind: `toCall: 2000000, toRaise: 4000000`
- Big Blind: `toCall: 0, toRaise: 2000000`

These value pairs don't match any of the two options above. 

I am confused. Which option does the backend use?

**Comment by sg777** [comment]
I made the changes in my latest commits, to reflect those changes, now fixing other crashing issues. If you can able to play the game, please check.

**Comment by norbertdragan** [comment]
I pulled and recompiled, but still got `BET_process_rest_method:1143::maxplayers:2Aborted (core dumped)` straight up. 😦

**Comment by norbertdragan** [comment]
I'm stuck with this error, can't go past. Happens after I press Start, same as #37.

**Comment by sg777** [comment]
Since we fixed the crashing issues, can you please test and see if this issue still exists
