### ISSUE TITLE
Rename toRaise to minRaiseTo

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#33]
I suggest that we rename toRaise message that the backend sends to minRaiseTo, so it is more clear what this value does.

I have renamed this property on the frontend from minRaise to minRaiseTo.

**Comment by norbertdragan** [comment]
I suggest that we rename `toRaise` message that the backend sends to `minRaiseTo`, so it is more clear what this value does. 

I have renamed this property on the frontend from `minRaise` to `minRaiseTo`.

**Comment by sg777** [comment]
Hi,

I renamed roRaise to minRaiseTo, in the following commit:
https://github.com/sg777/bet/commit/1a19e723853354c6cbc01a4d4223088b40e37973

Thank You.

**Comment by norbertdragan** [comment]
Thanks!
