### ISSUE TITLE
Player crashed after blinds were put in

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#34]
Player 1 crashed.

Pastebin: https://pastebin.com/E6WePbfz

Screenshot: http://i.norbert.dev/019c9d

**Comment by norbertdragan** [comment]
Player 2 crashed.

- Pastebin: https://pastebin.com/nbBYUhKJ
- Game: http://i.norbert.dev/41ccfb
- Terminals: http://i.norbert.dev/16324b

**Comment by sg777** [comment]
Since the issue is with improper handling of communication between the threads,  I fixed this crashing issue in the latest commit. Please check and revert if the issue persists.
