### ISSUE TITLE
DCV Crashes - "Table is Filled"

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#35]
After both players join, DCV crashes.

`BET_p2p_hostcommand::3305::bet->numplayers::2::bet->maxplayers::2Table is filled
Segmentation fault (core dumped)`

- Game: http://i.norbert.dev/c0076c
- Terminals: http://i.norbert.dev/0c90a4

**Comment by sg777** [comment]
Since the issue is with improper handling of communication between the threads,  I fixed this crashing issue in the latest commit. Please check and revert if the issue persists.
