### ISSUE TITLE
DCV crashed when clicking on Start

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#37]
The DCV crashed when I tried to start a new game, right after clicking on "Start".

`bet` is at commit `f7ad531e6d235e08e1b88d5149da3821fbde1726`

Terminal log: https://pastebin.com/vVP6pYLt

**Comment by norbertdragan** [comment]
Same thing happens every time I click "Start".

**Comment by sg777** [comment]
Since the issue is with improper handling of communication between the threads,  I fixed this crashing issue in the latest commit. Please check and revert if the issue persists.
