### ISSUE TITLE
Table is Filled

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#38]
I tested again with our nodes today.

I was able to play 1 game. When I pressed raise pre-flop, the core dumped. I suspect it's because I might be sending an illegal message to the backend - we were changing the schema previously.

When I tried to play another hand to debug, I was unable to play a new game. `Table is filled` - this is the error message that I have been receiving for the past 2 weeks. 

I was always able to play the first hand, and never able to play the second. To me, it seems like that at the backend the game is "still going on", and I am unable to connect again, because the table is filled. When I try it again the next day, I can play another hand again.

Video recording of this issue: http://i.norbert.dev/f4e57a

**Comment by sg777** [comment]
`Table is filled` is a log message that gets displayed on the console once the players joined the table. After this deck shuffling happens and generally it takes 2 to 3 seconds in the backend.
