### ISSUE TITLE
Dealer button doesn't move

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#40]
The dealer is always `player1`. It should move forward every time a next hand is dealt.

**Comment by sg777** [comment]
Yes agreed. I fixed that issue in the following commit ID: https://github.com/sg777/bet/commit/0aa842b5ef4aa287ec287f2d78e9ed8370e7a4f3.
Thank you.

**Comment by sg777** [comment]
Since now the dealer button moving, im closing this issue.
