### ISSUE TITLE
All-in keeps the game going

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#47]
When both players go all-in, the game goes to the next street and the game continues.

The expected behavior here is to deal all cards and select the winner.

Screenshot (click to enlarge): 
<a href="http://i.norbert.dev/0b614e" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0W2B2V2B0H0I0B453C3N/Image%202019-10-01%20at%206.50.05%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by sg777** [comment]
Hi,

Now I made changes to push the round_betting method info to all the active players.

Regards,
sg777.
