### ISSUE TITLE
Websocket doesn't receive message after player folds pre-flop

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#49]
Consider the following scenario:

1. Cards are dealt
2. `player1` folds
3. `player2` wins
4. New hand starts after players receiving `reset`

For step 4, both players has to send `player_join` to the back-end nodes. `player1` can successfully send the message, however, player2, who most was the winner of the previous cannot send any messages to the back-end node via WebSocket.

This breaks the game unfortunately.

**Comment by sg777** [comment]
I see at the GUI both the players are receiving reset, but not sure for 1 player why the GUI is not sending the `player_join` to the back end. When I checked I didn't see any breakage in the web-socket link after the reset sent to GUI. 
Can you please check at the GUI and let me know if it's expecting anything from the back end.

**Comment by norbertdragan** [comment]
I tested and it only happens when the first action is `fold`. 

**When it happens:**
1. Player1 folds
2. Player2 wins

**When it doesn't happen and the `player_join` is sent properly**
1. Player1 raises
2. Player2 folds

Or:

1. Player1 calls
2. Player2 raises
3. Player1 folds

Or:

1. Player1 calls
2. Plazer1 fold

Or any other scenario.

**Comment by norbertdragan** [comment]
Solved by norbertdragan/chips-poker-frontend@530eb0e. It was an issue at the front-end.
