### ISSUE TITLE
Players show the cards after a fold

### ISSUE THREAD

**Issue by norbertdragan** [sg777/bet#55]
Scenario:
- player1 raises
- player2 folds
- finalInfo shows both player's cards

The only time player cards are being shown are:
- If players call each other's bets on the river
- Both players are all-in

We should not send finalInfo with the boardCards in this other scenario.

**Comment by norbertdragan** [comment]
@sg777 seems like this has not been fixed yet

**Comment by sg777** [comment]
if any of the player folds, im sending the finalInfo as below
`
method: "finalInfo"
showInfo:
allHoleCardsInfo: Array(2)
0: (2) [null, null]
1: (2) [null, null]
length: 2
__proto__: Array(0)
boardCardInfo: (5) [null, null, null, null, null]
__proto__: Object
`
Can you please check and let me know in which scenario you are still able to view the cards.
